to_receive:
  user_name: insignia-site
  password: b2776d02fd87b463
  address: mailtrap.io
  port: 2525
  authentication: plain

to_send:
  address: smtp.gmail.com
  port: 587
  user_name: username@example.com
  password: password
  authentication: plain
  enable_starttls_auto: true

  # address:        ENV["#{name}_ADDRESS"],
  #       port:           ENV["#{name}_PORT"],
  #       domain:         ENV["#{name}_DOMAIN"],
  #       authentication: ENV["#{name}_AUTHENTITACION"],
  #       user_name:      ENV["#{name}_USER_NAME"],
  #       password:       ENV["#{name}_PASSWORD"]

  #       :enable_starttls_auto => true,  
  # :address            => 'smtp.gmail.com',
  # :port               => 587,
  # :tls                  => true,
  # :domain             => 'gmail.com', #you can also use google.com
  # :authentication     => :plain,
  # :user_name          => 'jatinkumar.nitk@gmail.com',
  # :password           => '_secret_password'