development:
  to_send:
    ActionMailer::Base.smtp_settings = {
    :user_name => "insignia-site",
    :password => "b2776d02fd87b463",
    :address => "mailtrap.io",
    :port => 2525,
    :authentication => :plain,
  }

test:
  ...

production:
  website1:
    domain: "gary@superfriends.com"
    user_name: gary
    password: superduper
    address: smtp.gmail.com
    port: 587
    authentication: :plain

  website2:
    domain: mysupercooldomain.com
    user_name: ABCDEF
    password: blahblah
    address: mail.authsmtp.com
    port: 25
    authentication: :plain